{{- if .Values.restdefinitions.gitrepository.enabled }}
kind: RestDefinition
apiVersion: ogen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-gitrepository
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-gitrepository/gitrepository.yaml
  resourceGroup: azuredevops.ogen.krateo.io
  resource: 
    kind: GitRepository
    identifiers:
    - name # Within the same project, the name of a GitRepository must be unique, so we can use it as an identifier.
    additionalStatusFields:
    - id
    - remoteUrl
    - sshUrl
    - url
    - defaultBranch
    verbsDescription:
    - action: create
      method: POST
      path: /api/{organization}/{projectId}/git/repositories # plugin endpoint
    - action: findby
      method: GET
      path: /{organization}/{projectId}/_apis/git/repositories
    - action: get
      method: GET
      path: /{organization}/{projectId}/_apis/git/repositories/{id}
    - action: update
      method: PATCH
      path: /{organization}/{projectId}/_apis/git/repositories/{id}
    - action: delete
      method: DELETE
      path: /{organization}/{projectId}/_apis/git/repositories/{id}
    configurationFields:
    - fromOpenAPI:
        name: api-version
        in: query
      fromRestDefinition:
        actions: ["*"] # star means all actions set in the verbsDescription above
{{ end }}
