{{- if .Values.restdefinitions.pipeline.enabled }}
kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-pipeline
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-pipeline/pipeline.yaml
  resourceGroup: azuredevops.kog.krateo.io
  resource: 
    kind: Pipeline
    identifiers:
    - id
    - url
    - name
    #- _links.self.web        # not working
    #- _links.self.web.href   # not working
    additionalStatusFields:
    - revision
    verbsDescription:
    - action: create
      method: POST
      path: /{organization}/{project}/_apis/pipelines
    - action: findby
      method: GET
      path: /{organization}/{project}/_apis/pipelines
    - action: get
      method: GET
      path: /api/{organization}/{project}/pipelines/{id} # plugin endpoint
    - action: update
      method: PUT
      path: /api/{organization}/{project}/pipelines/{id} # plugin endpoint
    - action: delete
      method: DELETE
      path: /api/{organization}/{project}/pipelines/{id} # plugin endpoint
{{ end }}
