apiVersion: azuredevops.ogen.krateo.io/v1alpha1
kind: PipelinePermission
metadata:
  name: test-pipelinepermission-kog-queue
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  configurationRef:                     # Reference to a PipelinePermissionConfiguration CR that contains the authentication information.
    name: my-pipelinepermission-config
    namespace: default 
  
  api-version: 7.2-preview.1
  
  organization: "krateo-kog"
  project: "test-project-1"
  resourceType: "queue" 
  resourceId: "38"

  allPipelines:
    authorized: false
  pipelines:
    - id: 6
      authorized: true
    - id: 4
      authorized: true

