apiVersion: azuredevops.ogen.krateo.io/v1alpha1
kind: PipelinePermission
metadata:
  name: test-pipelinepermission-kog-environment
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  configurationRef:                     # Reference to a PipelinePermissionConfiguration CR that contains the authentication information.
    name: my-pipelinepermission-config
    namespace: default 

  api-version: 7.2-preview.1
  
  organization: "krateo-kog"
  project: "test-project-1-classic"
  resourceType: "environment" 
  resourceId: "7"

  allPipelines:
    authorized: true

  pipelines:
    - id: 14
      # authorized: true is not required to be set here, since it is already the default value (and `authorized: false` is not allowed)
    - id: 15
